### ISSUE TITLE
Canvas的aliginWitnSceen()方法未在文档中

### ISSUE THREAD

**Issue by fkworld** [cocos-creator/creator-api-docs#108]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Canvas.md

在根据实际屏幕大小cc.winSize动态修改canvas适配方式时，如果仅修改fitHeight和fitWidth还不够，还需要应用alignWithScreen()方法。此方法既不在代码提示中，也不在文档中，但是在源码中。
参考源码：
https://github.com/cocos-creator/engine/blob/915ccf4e6e273f9003c14560ab1e48f9fa090132/cocos2d/core/components/CCCanvas.js#L198
参考代码（ts）：
```
  /**
     * 调整屏幕适配
     * @param canvas 
     * @param design_screen_radio 屏幕设计大小；目前从C中获取，未来也可以从canvas中获取
     * @param now_screen_radio 
     */
    adjust_screen(canvas, design_screen_radio,now_screen_radio ) {
        canvas.fitHeight = !(now_screen_radio > design_screen_radio)
        canvas.fitWidth = now_screen_radio > design_screen_radio
        canvas.alignWithScreen()
    }
```

建议将此方法补充到文档中。

**Comment by jareguo** [comment]
谢谢反馈，我们比较少用户会动态修改这两个值，我们内部在修改时，自动调用一次 alignWithScreen 吧，用户就不用手动调用了。
