### ISSUE TITLE
PDF manual for Cocos creator

### ISSUE THREAD

**Issue by Steph155** [cocos-creator/creator-api-docs#110]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/en/index.md

Greetings guys. I was wondering, why don't you provide a simple pdf manual to go in-depth with the engine and learn how to use it ? You must provide both a website and a downloadable pdf for the documentation. Cocos is licensed under MIT I've heard. It's the same with Godot engine, but they have a download link for both HTML and PDF documentation. I don't congratulate you guys, check this link for yourself and look for the section "Read the docs" in bottom left corner of the page. 
https://docs.godotengine.org/en/3.0/

**Comment by jareguo** [comment]
Sorry, we don't have enough people to do that. If you need a pdf, please checkout the git repo and build yourself. Please following this guide: https://toolchain.gitbook.com/ebook.html
