### ISSUE TITLE
https://docs.cocos.com/creator/api/zh/classes/_BaseNode.md

### ISSUE THREAD

**Issue by yanguoyu** [cocos-creator/creator-api-docs#114]
好像_BaseNode.md不存在呢。

**Comment by yanguoyu** [comment]
https://github.com/cocos-creator/creator-api-docs/blob/master/zh/modules/cc.md

**Comment by yanguoyu** [comment]
https://github.com/cocos-creator/creator-api-docs/blob/master/zh/modules/cc.md
这个里面的_BaseNode.md 404

**Comment by jareguo** [comment]
已修复，谢谢反馈
