### ISSUE TITLE
建议多分几个模块

### ISSUE THREAD

**Issue by xingluofenfen** [cocos-creator/creator-api-docs#115]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/index.md
绝大多数类和方法都放在cc模块下了，比如我现在想找Tween相关的API，这些API没有整合在一个模块下，找起来就很费劲。

**Comment by jareguo** [comment]
谢谢反馈，这里涉及到不少易用性还有兼容 Cocos2d-x 使用习惯的问题。你说的 API 应该是 Action 相关的，由于历史原因没办法调整，这块我们已经打算废弃了。Creator 这边新增的 API 都有注意这个问题。像是 cc.macro, cc.js, cc.Class ，都是新的模块。我们后面新增的 tween API 也会注意这个问题。
