### ISSUE TITLE
Vec2.sub 文档有错

### ISSUE THREAD

**Issue by zboboan** [cocos-creator/creator-api-docs#133]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Vec2.md

 var v = cc.v2(10, 10);
 v.sub(cc.v2(5, 5)); 
 var v1;
 v.sub(cc.v2(5, 5), v1); 

Vec2.sub  如果像官说的这样定义 v1 最后打印v1的值是 undefined
最后测试，如果var v1={};  最后才可以保存值（亲测）

同理，保存值的方法都有同样的错吧（没有测）

**Comment by xunyi0** [comment]
感谢反馈，已更正
