### ISSUE TITLE
Node方法getDisplayedColor介绍写的和getDisplayedOpacity一模一样

### ISSUE THREAD

**Issue by yinchenghc** [cocos-creator/creator-api-docs#14]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Node.md
![image](https://user-images.githubusercontent.com/16238547/34080445-2780f030-e379-11e7-836c-8cdf892896ab.png)

**Comment by jareguo** [comment]
谢谢哥
