### ISSUE TITLE
cc.color 的例子显示报错信息啦

### ISSUE THREAD

**Issue by Libnezz** [cocos-creator/creator-api-docs#141]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/modules/cc.md

Not found for the example path: temp-src/engine/docs/utils/api/engine/docs/cocos2d/core/value-types/CCColor/color.js
![image](https://user-images.githubusercontent.com/24961889/61194543-add29180-a6f4-11e9-8ef1-ddaec3cdde70.png)

**Comment by xunyi0** [comment]
已修复，感谢反馈～～
如果仍有问题的话，欢迎继续反馈哦～
