### ISSUE TITLE
RenderTexture

### ISSUE THREAD

**Issue by JohnSmithEarl** [cocos-creator/creator-api-docs#155]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/RenderTexture.md

api变了不知道怎么使用, 能给个例子吗?

**Comment by Jno1995** [comment]
请参考 CocosCreator 官方测试例中 ：
https://github.com/cocos-creator/example-cases/tree/2.2.0/assets/cases/07_capture_texture
，你也可以直接通过 CocosCreator 的 dashboard 界面创建 examples 项目，然后找到相应场景查看参考。
![image](https://user-images.githubusercontent.com/35944775/68919657-dc00d480-07ad-11ea-944e-bc9640bdeb32.png)
