### ISSUE TITLE
Document error

### ISSUE THREAD

**Issue by aboelf** [cocos-creator/creator-api-docs#157]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Node.md

> getComponent
> [:memo:](https://github.com/cocos-creator/creator-api-docs/edit/master/zh/classes/Node.md#L134 "Edit") <https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Node.md#L134>

**Comment by jareguo** [comment]
怎么了？

**Comment by aboelf** [comment]
// get sprite component.
var sprite = node.getComponent(cc.Sprite);
// get custom test calss.
var test = node.getComponent("Test");

**Comment by jareguo** [comment]
抱歉眼拙，请问错误在什么地方？正确的应该是什么样的？

**Comment by jareguo** [comment]
感谢，已修复

**Comment by aboelf** [comment]
不是明显的问题，是注释上class写成calss，
