### ISSUE TITLE
audioEngine

### ISSUE THREAD

**Issue by luzeping966** [cocos-creator/creator-api-docs#168]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/audioEngine.md

> c.audioEngine.getEffectsVolume()
> [:memo:](https://github.com/cocos-creator/creator-api-docs/edit/master/zh/classes/audioEngine.md#L622 "Edit") <https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/audioEngine.md#L622>

1. 定义
```
properties: {
     bg: {
        default: null,
        type: cc.AudioClip
     }
}
```
2. 使用
```
onLoad(){
    cc.audioEngine.playMusic(this.bg, true);
}
```
* 使用谷歌浏览器 第一次进入浏览器可以播放声音，
* 在浏览器界面刷新之后就没有声音，使用cc.audioEngine.isMusicPlaying(this.bg)检测是true
* 音量也设置了cc.audioEngine.setVolume(this.bg, 0.8)
* 后面放在遨游浏览器就没有问题 
* 谷歌浏览器是否要加什么方法？

**Comment by jareguo** [comment]
请移步论坛，方便我们跟进问题 https://forum.cocos.org/c/Creator 记得根据发帖模板提供必要信息，谢谢！
