### ISSUE TITLE
audioEngine

### ISSUE THREAD

**Issue by LiuYingJie** [cocos-creator/creator-api-docs#174]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/audioEngine.md

bug1:
设置背景音乐音量为0
观看qq小游戏平台的广告,回来
会出现背景音乐音量会设置回来

出现版本
2.2.2(当前我们项目使用)
2.3.4(最新引擎版本)

观看qq小游戏广告我们做了的处理:
播放广告,调用cc.game.pause()
关闭广告,调用cc.game.resume()

bug2:
设置背景音乐,音效 音量都为0,
观看玩qq小游戏平台的广告
设置音效的音量为1,背景音乐也会响起来

**Comment by jareguo** [comment]
抱歉我们不支持 QQ 小游戏，如果问题在微信小游戏上也存在，请在 [论坛](https://forum.cocos.org/c/Creator) 反馈一下，我们帮助排查一下。如果微信没问题，说明是 QQ 的 bug，请向 QQ 反馈。
