### ISSUE TITLE
Button按钮绑定事件API文档出错cc.Node.EventType.TOUCH_Move

### ISSUE THREAD

**Issue by jiamakong** [cocos-creator/creator-api-docs#178]
URL : https://docs.cocos.com/creator/api/zh/classes/Button.html?h=cc.node.eventtype.touch_move
API version:2.0

问题：

按钮可以绑定事件（但是必须要在按钮的 Node 上才能绑定事件）：
以下事件可以在全平台上都触发：

cc.Node.EventType.TOUCH_START // 按下时事件
cc.Node.EventType.**TOUCH_Move** // 按住移动后事件
cc.Node.EventType.TOUCH_END // 按下后松开后事件
cc.Node.EventType.TOUCH_CANCEL // 按下取消事件

更正：
It should be write :cc.Node.EventType.**TOUCH_MOVE** // 按住移动后事件

**Comment by jareguo** [comment]
谢谢反馈~
