### ISSUE TITLE
cc.AssetManager

### ISSUE THREAD

**Issue by OriginalStudio** [cocos-creator/creator-api-docs#179]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/modules/cc.AssetManager.md

关于cc.AssetManager.loadBundle 在加载同一个远端bundle文件时候，如果有两个显示节点(一大一小，类似PPT那种左侧栏和主显示区)都调用改loadBundle方法，后调用的回调会报错(加载本地bundle则不会有这个问题)。 虽然可以通过前者加载，后者用getBundle获取来解决，但同时加载相同远端bundle的报错问题毕竟是存在的。(期待得到官方答复，并告知问题原因，如果需要协助复现，可以加我QQ：489588952)

![截图](https://user-images.githubusercontent.com/25580361/91285241-8ab35600-e7bf-11ea-864a-057f9afbf6d1.jpeg)
![err](https://user-images.githubusercontent.com/25580361/91285279-999a0880-e7bf-11ea-8eb0-470a23694054.jpeg)

**Comment by holycanvas** [comment]
2.4.3 应该修复了，麻烦用2.4.3试试

**Comment by jareguo** [comment]
等待测试结果~ 先 close，如果还有问题可以在 reopen~
