### ISSUE TITLE
Sprite

### ISSUE THREAD

**Issue by trantoi99** [cocos-creator/creator-api-docs#184]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/en/classes/Sprite.md
Can you give example that is helpful???

**Comment by xunyi0** [comment]
@trantoi99 what version of Creator are you using? What example do you want?

**Comment by trantoi99** [comment]
I am using v2.4 .
Can you give me some example about loading images with typescript ?
Many thanks
