### ISSUE TITLE
Rect

### ISSUE THREAD

**Issue by zhaoxinming** [cocos-creator/creator-api-docs#19]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Rect.md

> var a = new cc.Rect(0, 0, 10, 10);
> var b = new cc.Rect(0, 0, 20, 20);
> a.containsRect(b);// true
> [:memo:](https://github.com/cocos-creator/creator-api-docs/edit/master/zh/classes/Rect.md#L377 "Edit") <https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Rect.md#L377>

var a = new cc.Rect(0, 0, 10, 10);
var b = new cc.Rect(0, 0, 20, 20);
a.containsRect(b);// true   这怎么能是true呢 ？这么重要的文档也能写错呀？

**Comment by jareguo** [comment]
您批评的是！
