### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by BigfishInSky** [cocos-creator/creator-api-docs#21]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Animation.md

Maybe 'lastframe' in animation events is not work， i debuged it in example-case-master of cocos,  it been registered, but  i do really how to trigger it.

**Comment by jareguo** [comment]
代码贴上来看看，动画是不是循环次数没有大于 一

**Comment by BigfishInSky** [comment]
哈哈，报告大神，我用的示例代码设置监听的是这一段，回调函数都没出问题
 onEnable: function () {
        var animation = this.animation;

        animation.on('play',      this.onPlay,        this);
        animation.on('stop',      this.onStop,        this);
        animation.on('lastframe', this.onLastFrame,   this);
        animation.on('finished',  this.onFinished,    this);
        animation.on('pause',     this.onPause,       this);
        animation.on('resume',    this.onResume,      this);
    },
在编辑器中将wrapmode设置为loop或者pingpong，是lastframe还需要额外设置AnimationState吗

**Comment by 2youyou2** [comment]
你在示例里面测试有问题吗？不行就上个 demo 来看看吧

**Comment by BigfishInSky** [comment]
[testAnimation.zip](https://github.com/cocos-creator/creator-api-docs/files/1702798/testAnimation.zip)
谢谢啦

**Comment by jareguo** [comment]
这边是一个可能的修复方法： http://discuss.cocos2d-x.org/t/lastframe-not-happening-anymore-in-1-7/40603/7?u=jare
我们会尽快验证这个问题

**Comment by BigfishInSky** [comment]
谢谢

**Comment by jareguo** [comment]
已修复，谢谢反馈
