### ISSUE TITLE
Vec2 的说明文档有错

### ISSUE THREAD

**Issue by justinlm** [cocos-creator/creator-api-docs#23]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Vec2.md

mulSelf 缩放当前向量。如果你想结果保存到另一个向量，可使用 mul() 代替。
mul 缩放当前向量，并返回新结果。
scaleSelf 分量相乘。
scale 分量相乘，并返回新的结果。

这里的说明 应该写错了。

**Comment by jareguo** [comment]
请问具体是指哪部分写错了？

**Comment by justinlm** [comment]
不好意思，我自己理解错误。谢谢。
