### ISSUE TITLE
loader

### ISSUE THREAD

**Issue by Luoyuda** [cocos-creator/creator-api-docs#26]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/loader.md
我就想知道，为什么部分api的解释是英文的，部分api又是中文解释的，看不懂你们的骚操作啊。。。

**Comment by jareguo** [comment]
哈哈，抱歉，历史原因…… 我们最近有在翻译了啊，如果有缺漏，麻烦 @CocosAss 有空在引擎中补充下（提交到 next 分支）
