### ISSUE TITLE
MouseJoint

### ISSUE THREAD

**Issue by rafnogueira** [cocos-creator/creator-api-docs#28]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/en/classes/MouseJoint.md

We Need more example codes in the definitions like in C++ documentation, I'm trying to add in javascript the physics component MouseJoint via code, and set the node to always be atached to mouse position with a invisible node created in position  of the touch,  but I can't understand how to do it I read but I can't understand

**Comment by 2youyou2** [comment]
You can take a look at this example :
https://github.com/2youyou2/physics-example/blob/master/assets/cases/utils/physics-bound.js#L20
