### ISSUE TITLE
MotionStreak

### ISSUE THREAD

**Issue by justinlm** [cocos-creator/creator-api-docs#31]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/MotionStreak.md

![image](https://user-images.githubusercontent.com/764048/39394201-a906a02e-4b01-11e8-849d-e20dc7288b24.png)

这里的描述是不是有点问题.
reset 方法的示例写的是：
// stop particle system.
myParticleSystem.stopSystem();

**Comment by ColinCollins** [comment]
增添问题： MotionStreak.md 页面链接错误 + 追踪链接错误指向 ParticleSystem
