### ISSUE TITLE
在代码链接中加入 commit id

### ISSUE THREAD

**Issue by jareguo** [cocos-creator/creator-api-docs#34]
现在源代码的地址，是这样的形式

![image](https://user-images.githubusercontent.com/1503156/39910454-049a1b96-552a-11e8-9bae-ff94928f911f.png)

这是错的。分支不对。而且没有加上 commit 值。

需要在生成 md 时，把 “master” 替换成 commit id，类似

```
https://github.com/cocos-creator/engine/blob/3a28f21eb9dcb536d667cafaba8999cd9a7258d9/cocos2d/actions/CCActionInterval.js#L272
```

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/40468605-7a824c8a-5f60-11e8-8b5b-f692d6ab7c43.png)
增添完善部分：修改 API 链接显示部分，修正因为添加 commit-id 导致的链接显示不全问题
