### ISSUE TITLE
RigidBody

### ISSUE THREAD

**Issue by 173198205** [cocos-creator/creator-api-docs#38]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/RigidBody.md
applyLinearImpulse这个方法怎么无论使用多大的“冲量”都只能跑到固定的距离就停下了？linearDamping不为0；我使用是只调用一次applyLinearImpulse这个方法（直接给他足够的冲量），并不是在类似update里面每帧调用。我是不是用错了？

**Comment by 2youyou2** [comment]
你设置了 applyLinearImpulse 后 update 里打印下 linearVelocity 看下有变化么

**Comment by 173198205** [comment]
有的，一直在变小，但最终也不是变成0速度

**Comment by 173198205** [comment]
对了，我发现无论给的applyLinearImpulse有多大，打印出来的速度变化区别都不大，给小的和给大的出来的速度好像区别不明显

**Comment by 173198205** [comment]
我对linearVelocity直接赋值cc.p(1000000,1000000)打印出来的linearVelocity只有（3500，3500）大概的样子。。

**Comment by 173198205** [comment]
速度是可以到0的。。但是现象还是像我说的，固定距离就停下了。可能是我不会用吧

**Comment by 2youyou2** [comment]
不太明白你想说什么。。。
冲量只是瞬间给个力，就像你踢足球一样，给一脚当然只能滚一定距离了。
你要持续跑动的话，应该持续给他一个力

**Comment by 173198205** [comment]
我意思是我给10万的力能踢到1000米，但是我用100万的力也只能踢到1000米。。。

**Comment by 2youyou2** [comment]
https://github.com/2youyou2/physics-example/blob/master/assets/cases/example/linear-impulse.js

我测试可以明显看到差距呢

**Comment by 173198205** [comment]
比如linearDamping=1的时候，距离就固定了

**Comment by 173198205** [comment]
linearDamping有值的时候，总会有一个固定好的距离，加大冲量也不能超过这个距离，这是正常的吗？我物理不太好，但是感觉有违常理。。
