### ISSUE TITLE
API 文档需显示 mixins

### ISSUE THREAD

**Issue by jareguo** [cocos-creator/creator-api-docs#64]
目前 mixins 属性都不会在 API 文档中显示出来，例如

http://docs.cocos.com/creator/api/zh/classes/ArmatureDisplay.html?h=armaturedisplay

mixin 了 event target，但是并没有 off 的 API 定义

**Comment by ColinCollins** [comment]
不是特别明白???

**Comment by jareguo** [comment]
先放着吧，有空再做这个

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/44512237-71690200-a6ec-11e8-8de4-bb6beafc80be.png)
mixins 内容是有显示的。
dragonBones 那个文件是没有显示的。在 1.9 有两个文件内容 CCArmatureDisplay.js 这个内容本身没有注释，所以是没有这篇 API 文档的，有个同名内容叫 ArmatureDisplay.js
