### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by kibernet** [cocos-creator/creator-api-docs#68]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/index.md

2.0版本的 creator 的TypeScript 的声明文件creator.d.ts 中的
FiniteTimeAction类的reverse方法的返回值不应该是void，应该修改为FiniteTimeAction。

**Comment by ColinCollins** [comment]
非常感谢您的热心提交，希望日后依然可以在论坛，仓库看到您积极研发的身影。这个问题我们会立马修正的。:·)

**Comment by ColinCollins** [comment]
目前检查了您说的 API 返回值是正常的，因为本身作为基类的它是不会被直接调用的。但是仍然感谢您的提交，谢谢您一直以来的支持，希望以后仍然能看见您坚持研发的英姿。:~)

**Comment by kibernet** [comment]
如果不修改，调用reverse方法，在vscode里面编译报错。

**Comment by kibernet** [comment]
如果不修改，调用reverse方法，在vscode里面编译报错。
并且clone方法返回值也是FiniteTimeAction，建议修改reverse返回值为FiniteTimeAction。
