### ISSUE TITLE
CCAudioEngine.js中的setFinishCallback方法实现有错误

### ISSUE THREAD

**Issue by kibernet** [cocos-creator/creator-api-docs#79]
2.0版本
CCAudioEngine.js中的setFinishCallback方法实现有错误，当设置回调后，audio之前默认注册的endcallback会被抹掉，导致不会recycleAudio.以至于达到音频实例上限后，即使注册回调也不会触发回调了。
修改如下
```
    setFinishCallback: function (audioID, callback) {
        var audio = getAudioFromId(audioID);
        if (!audio)
            return;
        // yuanjun add
        audio._callbackTable.ended.callbacks.unshift(callback)
        audio._callbackTable.ended.targets.unshift(audio)
        audio.on('ended', audio._finishCallback);
        */
    },
```

**Comment by VisualSJ** [comment]
你是在 setFinishCallback 内做了什么操作么？

这个接口在当初定义的时候因为一些原因，做成了只能绑定一个事件。
现在问题应该是超过播放上限之后，你在 callback 内定义的一些操作就无法触发了是么？

**Comment by knoxHuang** [comment]
非常感谢反馈，能否给一下能重现的范例给我们测试吗？

**Comment by PPpro** [comment]
目前的实现应该不会覆盖音频的回收操作了
只不过 finishCallback 因为底层实现的原因，暂时只支持监听一个回调，新注册的会覆盖旧的回调
可以在最新版本验证

感谢反馈
