### ISSUE TITLE
RigidBody

### ISSUE THREAD

**Issue by StrayInWorld** [cocos-creator/creator-api-docs#80]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/RigidBody.md

----------------------------------------------------------
getWorldVector

将一个给定的世界坐标系下的向量转换为刚体本地坐标系下的向量
----------------------------------------------------------

上面是getWorldVector的说明，是否有误。

**Comment by 2youyou2** [comment]
谢谢反馈~
