### ISSUE TITLE
Node 节点属性的倾斜角度解释写反了

### ISSUE THREAD

**Issue by jareguo** [cocos-creator/creator-api-docs#85]
麻烦验证下
http://forum.cocos.com/t/cocoscreateapi/65803

**Comment by ColinCollins** [comment]
![image](https://user-images.githubusercontent.com/35832931/45613070-a7a16380-ba97-11e8-9ca7-c0f6485dd8f7.png)
2.0 应该是已经修复过了，更新一下文档就 ok 了。
1.10 和 1.9 有同样的问题，但是似乎还没有修复过。要合并一下还是我直接每个分支改一下？

**Comment by ColinCollins** [comment]
@xunyi0

**Comment by jareguo** [comment]
1.10 和 1.9 的文档不用改了

**Comment by xunyi0** [comment]
API 官网已更新
