### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by zehon001** [cocos-creator/creator-api-docs#88]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/Layout.md

2.0.2版本 layout出现BUG
layout子节点一张图片和一个label
代码执行
this.txtCombo.string = "/"+3;
console.log(this.layout.node.width);
这里输出layout的width是-10（在onLoad输出271）

编辑器改了label的字符串之后也不会自动对齐

layout参数：
type : horizontal
resizeMode : container
Padding{left:0,right:0,SpacingX:10}
horizontal direction:LEFT_TO_RIGHT

**Comment by ColinCollins** [comment]
目前需要检测和修改的内容较多，因此可能不能及时的回复您的消息，非常抱歉。如果可以希望您能够主动的提供一个 demo，以便我们更直观的检测您所反馈的内容。

**Comment by ColinCollins** [comment]
当前官方仓库只接受 API 相关的 bug 反馈，为了更好的跟进您的 bug 反馈，建议您移步论坛发帖。
