### ISSUE TITLE
SystemEvent

### ISSUE THREAD

**Issue by aaaa1990aaaa** [cocos-creator/creator-api-docs#89]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/SystemEvent.md

这个模块不知道是我理解有问题  还是文档有问题所以请教一下
cc.SystemEvent.on(cc.SystemEvent.EventType.KEY_DOWN, function () {
            console.log('hello world')
        }, this)
这样写要报错   说on不是一个函数

cc.systemEvent.on(cc.SystemEvent.EventType.KEY_DOWN, function () {
            console.log('hello world')
        }, this)
最后把cc.SystemEvent.on改成小写的cc.systemEvent.on就对了  但是手册上面的大写

**Comment by ColinCollins** [comment]
http://docs.cocos.com/creator/api/zh/modules/cc.html#systemevent
systemEvent 是 SystemEvent 的一个实现， on 函数并不是静态函数，你不能通过一个 class 直接调用

**Comment by jareguo** [comment]
@ColinCollins 麻烦在 Class 那边说明一下，如何获取 SystemEvent 实例，附上一个范例。

**Comment by aaaa1990aaaa** [comment]
谢谢在百忙之中解答我的疑问
