### ISSUE TITLE
Where is 'audio' defined in cc.AudioSource? 

### ISSUE THREAD

**Issue by tlhinman** [cocos-creator/creator-api-docs#92]
I'm exploring Cocos Creator development using TypeScript. In the JavaScript version of the code, I can see a property of `cc.AudioSource` called `audio`, but this doesn't show up in the class's definition in `creator.d.ts`. Can someone explain what this is and where it's declared? Thank you.

**Comment by ColinCollins** [comment]
The 'audio' is a private variable, we do not suggest you use it straightly.
