### ISSUE TITLE
DistanceJoint

### ISSUE THREAD

**Issue by StrayInWorld** [cocos-creator/creator-api-docs#93]
URL : https://github.com/cocos-creator/creator-api-docs/blob/master/zh/classes/DistanceJoint.md

![image](https://user-images.githubusercontent.com/27119267/46589949-016adb80-cae2-11e8-8e48-dc27047c50f9.png)

DistanceJoint 的阻尼属性名写错了。

**Comment by ColinCollins** [comment]
感谢您的反馈，已修复：https://github.com/cocos-creator/engine/pull/3351
